// Code generated by Kitex v0.4.4. DO NOT EDIT.

package feedsrv

import (
	"context"
	"fmt"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
	feed "tiktok/kitex_gen/feed"
)

func serviceInfo() *kitex.ServiceInfo {
	return feedSrvServiceInfo
}

var feedSrvServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "FeedSrv"
	handlerType := (*feed.FeedSrv)(nil)
	methods := map[string]kitex.MethodInfo{
		"Feed":                                kitex.NewMethodInfo(feedHandler, newFeedArgs, newFeedResult, false),
		"GetVideosByVideoIdsAndCurrentUserId": kitex.NewMethodInfo(getVideosByVideoIdsAndCurrentUserIdHandler, newGetVideosByVideoIdsAndCurrentUserIdArgs, newGetVideosByVideoIdsAndCurrentUserIdResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "feed",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func feedHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(feed.DouyinFeedRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(feed.FeedSrv).Feed(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *FeedArgs:
		success, err := handler.(feed.FeedSrv).Feed(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*FeedResult)
		realResult.Success = success
	}
	return nil
}
func newFeedArgs() interface{} {
	return &FeedArgs{}
}

func newFeedResult() interface{} {
	return &FeedResult{}
}

type FeedArgs struct {
	Req *feed.DouyinFeedRequest
}

func (p *FeedArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(feed.DouyinFeedRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *FeedArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *FeedArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *FeedArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in FeedArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *FeedArgs) Unmarshal(in []byte) error {
	msg := new(feed.DouyinFeedRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var FeedArgs_Req_DEFAULT *feed.DouyinFeedRequest

func (p *FeedArgs) GetReq() *feed.DouyinFeedRequest {
	if !p.IsSetReq() {
		return FeedArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *FeedArgs) IsSetReq() bool {
	return p.Req != nil
}

type FeedResult struct {
	Success *feed.DouyinFeedResponse
}

var FeedResult_Success_DEFAULT *feed.DouyinFeedResponse

func (p *FeedResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(feed.DouyinFeedResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *FeedResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *FeedResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *FeedResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in FeedResult")
	}
	return proto.Marshal(p.Success)
}

func (p *FeedResult) Unmarshal(in []byte) error {
	msg := new(feed.DouyinFeedResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *FeedResult) GetSuccess() *feed.DouyinFeedResponse {
	if !p.IsSetSuccess() {
		return FeedResult_Success_DEFAULT
	}
	return p.Success
}

func (p *FeedResult) SetSuccess(x interface{}) {
	p.Success = x.(*feed.DouyinFeedResponse)
}

func (p *FeedResult) IsSetSuccess() bool {
	return p.Success != nil
}

func getVideosByVideoIdsAndCurrentUserIdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(feed.DouyinGetVideosByVideoIdsAndCurrentUserIdRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(feed.FeedSrv).GetVideosByVideoIdsAndCurrentUserId(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *GetVideosByVideoIdsAndCurrentUserIdArgs:
		success, err := handler.(feed.FeedSrv).GetVideosByVideoIdsAndCurrentUserId(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetVideosByVideoIdsAndCurrentUserIdResult)
		realResult.Success = success
	}
	return nil
}
func newGetVideosByVideoIdsAndCurrentUserIdArgs() interface{} {
	return &GetVideosByVideoIdsAndCurrentUserIdArgs{}
}

func newGetVideosByVideoIdsAndCurrentUserIdResult() interface{} {
	return &GetVideosByVideoIdsAndCurrentUserIdResult{}
}

type GetVideosByVideoIdsAndCurrentUserIdArgs struct {
	Req *feed.DouyinGetVideosByVideoIdsAndCurrentUserIdRequest
}

func (p *GetVideosByVideoIdsAndCurrentUserIdArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(feed.DouyinGetVideosByVideoIdsAndCurrentUserIdRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetVideosByVideoIdsAndCurrentUserIdArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetVideosByVideoIdsAndCurrentUserIdArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetVideosByVideoIdsAndCurrentUserIdArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in GetVideosByVideoIdsAndCurrentUserIdArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *GetVideosByVideoIdsAndCurrentUserIdArgs) Unmarshal(in []byte) error {
	msg := new(feed.DouyinGetVideosByVideoIdsAndCurrentUserIdRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetVideosByVideoIdsAndCurrentUserIdArgs_Req_DEFAULT *feed.DouyinGetVideosByVideoIdsAndCurrentUserIdRequest

func (p *GetVideosByVideoIdsAndCurrentUserIdArgs) GetReq() *feed.DouyinGetVideosByVideoIdsAndCurrentUserIdRequest {
	if !p.IsSetReq() {
		return GetVideosByVideoIdsAndCurrentUserIdArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetVideosByVideoIdsAndCurrentUserIdArgs) IsSetReq() bool {
	return p.Req != nil
}

type GetVideosByVideoIdsAndCurrentUserIdResult struct {
	Success *feed.DouyinGetVideosByVideoIdsAndCurrentUserIdResponse
}

var GetVideosByVideoIdsAndCurrentUserIdResult_Success_DEFAULT *feed.DouyinGetVideosByVideoIdsAndCurrentUserIdResponse

func (p *GetVideosByVideoIdsAndCurrentUserIdResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(feed.DouyinGetVideosByVideoIdsAndCurrentUserIdResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetVideosByVideoIdsAndCurrentUserIdResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetVideosByVideoIdsAndCurrentUserIdResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetVideosByVideoIdsAndCurrentUserIdResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in GetVideosByVideoIdsAndCurrentUserIdResult")
	}
	return proto.Marshal(p.Success)
}

func (p *GetVideosByVideoIdsAndCurrentUserIdResult) Unmarshal(in []byte) error {
	msg := new(feed.DouyinGetVideosByVideoIdsAndCurrentUserIdResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetVideosByVideoIdsAndCurrentUserIdResult) GetSuccess() *feed.DouyinGetVideosByVideoIdsAndCurrentUserIdResponse {
	if !p.IsSetSuccess() {
		return GetVideosByVideoIdsAndCurrentUserIdResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetVideosByVideoIdsAndCurrentUserIdResult) SetSuccess(x interface{}) {
	p.Success = x.(*feed.DouyinGetVideosByVideoIdsAndCurrentUserIdResponse)
}

func (p *GetVideosByVideoIdsAndCurrentUserIdResult) IsSetSuccess() bool {
	return p.Success != nil
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Feed(ctx context.Context, Req *feed.DouyinFeedRequest) (r *feed.DouyinFeedResponse, err error) {
	var _args FeedArgs
	_args.Req = Req
	var _result FeedResult
	if err = p.c.Call(ctx, "Feed", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetVideosByVideoIdsAndCurrentUserId(ctx context.Context, Req *feed.DouyinGetVideosByVideoIdsAndCurrentUserIdRequest) (r *feed.DouyinGetVideosByVideoIdsAndCurrentUserIdResponse, err error) {
	var _args GetVideosByVideoIdsAndCurrentUserIdArgs
	_args.Req = Req
	var _result GetVideosByVideoIdsAndCurrentUserIdResult
	if err = p.c.Call(ctx, "GetVideosByVideoIdsAndCurrentUserId", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
